### ISSUE TITLE
เขียน Feedback ที่ Present วันนี้ด้วยนะ

### ISSUE THREAD

**Issue by Thanaphat-Boonrak** [Thanaphat-Boonrak/INT100-G2-01#11]
@PoonpipatSr มีไรให้ช่วยบอกเด้อแล้วที่พิมในนี้จะได้ฝึกกันได้นะ

**Comment by Jaturapat07** [comment]
ปัญหาคืออาจจะมีวิธีแก้ปัญหาที่ดีกว่านี้

**Comment by ToeyToeiUni** [comment]
I Like
-ข้อมูลเยอะ
-นำเสนอดี
-รายละเอียดเยอะ
-วิธีในการแก้ปัญหา มีการเก็บรายละเอียดดี
-แก้ปัญหาได้น่าสนใจ
-เข้าใจในรายละเอียดของผู้ประสบปัญหา
-พูดนำเสนอได้ดี
-อธิบายได้เข้าใจถึงปัญหา

**Comment by PoonpipatSr** [comment]
I wish
การระบุปัญหาอาจจะให้มีความหลากหลายมากขึ้น

**Comment by PoonpipatSr** [comment]
I wish
ยังระบุปัญหาได้ไม่ชัดเจนแต่โดยรวมชอบมากครับ

**Comment by PoonpipatSr** [comment]
I wish
He speak less

**Comment by PoonpipatSr** [comment]
I like
วิเคราะห์ข้อมูลของ user ได้ดี

**Comment by PoonpipatSr** [comment]
I like
- The detail of an information
- How expert user information they get.

**Comment by PoonpipatSr** [comment]
I like
ข้อมูลแน่นมากครับ ในส่วนของ Journey map เห็นภาพได้ชัดเจนมากครับ

**Comment by Jaturapat07** [comment]
I wish
อยากให้พูดการแก้ไขปัญหาให้ชัดเจนกว่านี้

**Comment by Jaturapat07** [comment]
I wish
อยากให้สอบถาม User มากกว่านี้

**Comment by Jaturapat07** [comment]
I wish
ไม่ให้รถเข้ามาข้างใน

**Comment by Jaturapat07** [comment]
I wish
การแก้ปัญหาอาจจะมีค่าใช้จ่ายที่สูง

**Comment by Jaturapat07** [comment]
I wish
มองตัวหนังสือสไลด์ยาก

**Comment by Thanaphat-Boonrak** [comment]
I like
-การนำเสนอดี ไหลลื่น น่าฟัง
-ชอบการเล่าเรื่องที่ละเอียด รู้ปัญหาชัดเจนว่ามีอะไรบ้าง
-ข้อมูลดี ชัดเจน วิเคราะห์ได้ดี
-การนำเสนอตลกดี ข้อมูลละเอียด
-อธิบายรายละเอียดดี ชอบการให้ไปวิ่งในสเตเดี้ยม
-นำเสนอดี ข้อมูลครบ สรุปได้เข้าใจง่าย
-วิธีแก้ปัญหาดี
-ทำสไลด์ดี เล่าเรื่องเข้าใจง่าย

**Comment by AUUNNG** [comment]
### สิ่งที่ชอบ (I Like)
- ข้อมูลมีความละเอียดและครบถ้วน
- การนำเสนอมีความชัดเจนและน่าสนใจ
- วิธีการแก้ปัญหามีการเก็บรายละเอียดที่ดีและเข้าใจปัญหาของผู้ประสบปัญหา
- การวิเคราะห์ข้อมูลของผู้ใช้ (User) มีความเชี่ยวชาญ
- Journey Map มีความชัดเจนมาก
- การนำเสนอไหลลื่นและน่าฟัง
- การเล่าเรื่องละเอียดและการให้ตัวอย่างที่ดี

### สิ่งที่ต้องการปรับปรุง (I Wish)
- การระบุปัญหาควรมีความหลากหลายมากขึ้น
- การระบุปัญหายังไม่ชัดเจนเพียงพอ
- ต้องการให้พูดเกี่ยวกับการแก้ปัญหาให้ชัดเจนกว่านี้
- อยากให้สอบถามผู้ใช้มากกว่านี้
- ควรมีการห้ามรถเข้ามาข้างใน
- การแก้ปัญหาอาจมีค่าใช้จ่ายที่สูง
- ตัวหนังสือในสไลด์ยากที่จะอ่าน
- ผู้พูดควรพูดให้น้อยลง
