### ISSUE TITLE
FeedBack ของ ตัว Persona , Ideate , Point of view , Journy Map

### ISSUE THREAD

**Issue by Thanaphat-Boonrak** [Thanaphat-Boonrak/INT100-G2-01#43]

**Comment by Thanaphat-Boonrak** [comment]
I like:
ข้อมูลไอเดียดี
แนวคิดดี
แก้ปัญหาได้ตรงจุด
ทำได้มีระบบ
User Persona ละเอียดดี
มีตัวอย่างการแก้ปัญหาให้ดู
I wish 
เพิ่มระยะการจับตรวจ
พูดให้เสียงดังกว่านี้
สรุป Ideate ให้ชัดเจนกว่านี้

**Comment by AUUNNG** [comment]
### I wish

- การระบุ ค่อนข้างไม่ตรงกับการแก้ไขปัญหา
- เชื่อว่ามีวิธีแก้ที่ดีกว่านี้
- ไอเดียไปได้ดีกว่านี้
- อยากให้แก้เนื้อหาในบอร์ด
- วิธีแก้ปัญหาน่าสนใจแต่อาจต้องใช้เงินทุนค่อนข้างมากอยากให้ลองคำนวณเงินที่ต้องใช้สำหรับการติดตั้งอุปกรณ์ในการแก้ปัญหา
- อยากให้มี prototype
- แค่ให้นำป้ายและเอารั้วมากั้นไม่ให้รถเข้าน่าจะแก้ปัญหาได้ง่ายกว่า
- คิดว่าการแก้ปัญหาทำได้ยาก และกลัวว่าว่าจะ ใช่ไม่ได้จริง
- สายรัดข้อมือดูทำได้ยาก เกินไป
-  งบประมาณสูง

### I like

- ไอเดียดี
- สิ่งประดิษฐ์น่าสนใจ
- วิธีแก้ปัญหา
- การเขียนพรีเซ็นดูง่าย

**Comment by ToeyToeiUni** [comment]
Like
-ชอบวิธีแก้ไขปัญหา มีหลาย way ให้เลือก
-I Like Ideate.
-ชอบสายรัดข้อมือ เยี่ยมๆ
-การนำเสนอข้อมูลดูชัดเจนดี โดยรวมถือว่าดี
-การแก้ไขปัญหาดี ไอเดียหลากหลาย
-มีรูปตัวอย่างงาน ,อ่านง่ายตัวหนังสือใหญ่
-วิธีแก้ปัญหา
-Idea ดีและนำเสนอดี
-การพรีเซ้นท์ ,POV ,การเข้าใจปัญหา

I wish
-เสียงเบาไปนิด
-Journey Map ไม่ค่อยละเอียด
-ฟันฉลามอันตรายไปคิดว่าข้อนี้ตัดออกดีกว่า
-Idea แก้บางอย่างมีแนวโน้มที่ส่งผลกระทบต่อการสัญจร

**Comment by PoonpipatSr** [comment]
I like :
- เจาะลึกข้อมูลบุคคลเยอะดี
- ปัญหาที่นำเสนอค่อนข้างชัดเจน
- รายละเอียดดี
- Ideate ดี
- การพรีเซ้นดี
- มีสไลด์และภาพประกอบ
- ภาพวาดน่ารัก
- มีการแก้ปัญหาในหลายๆมุมชอบมากครับ
- ชอบไอเดีย

I wish : 
- อยากให้พูดหลักการแก้ไข
- อยากให้ระบุปัญหาที่หลากหลายขึ้น
- ระบุปัญหาให้ชัดเจน
- วิธีที่ทำให้รถวิ่งไปที่อื่นเราว่าไม่โอเค
- เสียงคนนำเสนอเบามากฟังยาก
- บางไอเดียทำยาก
- อยากให้มีระบบวัดชีพจรและวัดความดันได้
