### ISSUE TITLE
feedback  week 5

### ISSUE THREAD

**Issue by AUUNNG** [Thanaphat-Boonrak/INT100-G2-01#45]

**Comment by AUUNNG** [comment]
### i like
- ชอบที่รู้ว่าปัญหาควรแก้ยังไง
- present 11/10
- present เข้าใจง่าย
- ดูปลอดภัยดี
- วิธีแก้ปัญหาง่ายดีไม่ซับซ้อน

### i wish

- อยากให้ใช้แบริเออร์เป็นวัสดุอื่น
- อยากได้แบริเออร์เพิ่ม
- ที่จอดรถอาจมีไม่พอน่าจะมีที่จอดเยอะกว่านี้
- เปลี่ยนจากแบริเออร์พลาสติกเป็นปูนอาจจะไม่เกิดการผุพังได้ง่าย

**Comment by Thanaphat-Boonrak** [comment]
I like
- ชอบการพูดปัญหาแก้อย่างดี
- เก็บข้อมูลมาครบดี
- ความคิดไอเดียดีมาก
- เนื้อหาครบถ้วน
I wish
- prototype อยากให้ดูง่ายกว่านี้
- อยากให้ Prototype ชัดเจนกว่านี้

**Comment by ToeyToeiUni** [comment]
I like
-ดูทำได้จริง และใช้งบประมาณไม่มาก
-ชอบการแก้ปัญหา
-ชอบการนำรูปสถานที่จริงในการนำเสนอ
-ชอบปัญหาที่เลือกเพราะพบเจอได้ทั่วไป
-มีต้นทุนการแก้ปัญหาถูก ชอบการไปเก็บรูปศึกษาสถานที่จริง

I wish
-จำกัดชั่วโมงการจอด
-พุพังง่าย
-จำกัดชั่วโมงการจอด
-พูดช้า

**Comment by PoonpipatSr** [comment]
I like : 
- สไลด์ทำได้ดี
- การเล่าเรื่องโอเค
- ปิดไม่ให้รถเข้ามา
- present ดีข้อมูลครบการนำเสนอตลกดีข้อมูลละเอียด
- อธิบายละเอียดชอบการให้ไปวิ่งในสเตเดี้ยม
- การนำเสนอดี ลื่นไหล น่าฟัง
- ชอบการเล่าเรื่องที่ละเอียด รู้ปัญหาชัดเจนว่ามีอะไรบ้าง
- ข้อมูลละเอียด ชัดเจน
- การเข้าใจในรายละเอียดของผู้ประสบปัญหา

I wish : 
- เก็บตังรถที่เข้ามาจอดข้างใน
- ตัวหนังสือมองยาก
- ไม่ให้รถเข้ามาข้างในได้
- อยากให้ถามมากกว่านี้
- พูดไม่กระชับ
- คนวิ่งทุกที่เลย
- ให้บำรุงรักษาแบริเออร์อยู่ตลอด
- ให้มีบทลงโทษกับพวกที่มักง่าย
- อยากได้ storyboard มากกว่านี้
- เห็นด้วยที่ให้เพิ่มป้ายที่มีแสงให้คนมองเห็นได้ชัดเจน
